#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "api-base" # URL will be https://api-base.fly.dev/
primary_region = "ams" # data center location

# Pocketbase stores data locally in a SQLite database. 
# Therefore we need a persistent volume, which can be extended later.
# See https://fly.io/docs/reference/volumes/#extend-a-volume for further info.
[mounts]
  source = "pb_data"
  destination = "/pb_data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true # stops container when idling
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[http_service.concurrency]
  type = "requests"
  soft_limit = 500
  hard_limit = 550

[[http_service.checks]] # This health check ensures that only a healthy app will be deployed
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/health"
