# fly.toml app configuration file generated for api-base on 2023-07-28T13:13:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "api-base"
primary_region = "ams"

[mounts]
  source = "pb_data"
  destination = "/pb_data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true # stops when idling
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
  grace_period = "3s"
  interval = "20s"
  method = "GET"
  timeout = "5s"
  path = "/api/health"

